-- 1. 회원 테이블 (일반 사용자 및 관리자 통합)
CREATE TABLE USERS (
    USER_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMAIL           VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD        VARCHAR2(255) NOT NULL, -- 암호화된 비밀번호 저장
    NICKNAME        VARCHAR2(50)  NOT NULL UNIQUE,
    ROLE            VARCHAR2(20)  DEFAULT 'USER' NOT NULL, -- USER, ADMIN
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

-- 2. 카테고리 테이블
CREATE TABLE CATEGORIES (
    CATEGORY_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME            VARCHAR2(50) NOT NULL UNIQUE
);

-- 3. 라이딩 기록 관리 테이블 (GPX 및 운동 정보)
CREATE TABLE RECORDS (
    RECORD_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID         NUMBER NOT NULL,
    TITLE           VARCHAR2(100) NOT NULL,
    START_TIME      TIMESTAMP NOT NULL,
    END_TIME        TIMESTAMP NOT NULL,
    DURATION_MIN    NUMBER NOT NULL, -- 운동 시간(분 단위)
    DISTANCE_KM     NUMBER(5,2) NOT NULL, -- 라이딩 거리 (예: 999.99 km)
    GPX_DATA        CLOB, -- GPX XML/JSON 경로 데이터가 길어질 수 있으므로 CLOB 사용
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_RECORDS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- 4. 게시글 테이블
CREATE TABLE POSTS (
    POST_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID         NUMBER NOT NULL,
    CATEGORY_ID     NUMBER NOT NULL,
    RECORD_ID       NUMBER, -- 라이딩 기록 연동 (선택 사항)
    TITLE           VARCHAR2(200) NOT NULL,
    CONTENT         CLOB NOT NULL, -- 본문 데이터 대용량 처리를 위해 CLOB 사용
    VIEW_COUNT      NUMBER DEFAULT 0 NOT NULL,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_POSTS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_POSTS_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID),
    CONSTRAINT FK_POSTS_RECORD FOREIGN KEY (RECORD_ID) REFERENCES RECORDS(RECORD_ID) ON DELETE SET NULL
);

-- 5. 댓글 테이블
CREATE TABLE COMMENTS (
    COMMENT_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    POST_ID         NUMBER NOT NULL,
    USER_ID         NUMBER NOT NULL,
    CONTENT         VARCHAR2(1000) NOT NULL,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_COMMENTS_POST FOREIGN KEY (POST_ID) REFERENCES POSTS(POST_ID) ON DELETE CASCADE,
    CONSTRAINT FK_COMMENTS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- 6. 게시글 좋아요 테이블 (복합키 대신 기본 ID 사용, 유니크 제약 추가)
CREATE TABLE POST_LIKES (
    LIKE_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    POST_ID         NUMBER NOT NULL,
    USER_ID         NUMBER NOT NULL,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_POST_USER UNIQUE (POST_ID, USER_ID),
    CONSTRAINT FK_LIKES_POST FOREIGN KEY (POST_ID) REFERENCES POSTS(POST_ID) ON DELETE CASCADE,
    CONSTRAINT FK_LIKES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- 7. 사진/첨부파일 테이블
CREATE TABLE ATTACHMENTS (
    FILE_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    POST_ID         NUMBER NOT NULL,
    ORIGINAL_NAME   VARCHAR2(255) NOT NULL, -- 사용자가 올린 파일명
    STORED_NAME     VARCHAR2(255) NOT NULL, -- 서버나 S3에 저장될 고유 파일명 (UUID 등)
    FILE_PATH       VARCHAR2(500) NOT NULL, -- 파일 저장 경로 혹은 URL
    FILE_SIZE       NUMBER NOT NULL,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ATTACHMENTS_POST FOREIGN KEY (POST_ID) REFERENCES POSTS(POST_ID) ON DELETE CASCADE
);