spring.application.name=backend

# ==========================================================
# 1. ORACLE DATABASE SETTINGS (??? DB ?? ??)
# ==========================================================
# DB ?? ?? (Host: localhost, Port: 1521, SID: xe)
spring.datasource.url=jdbc:oracle:thin:@localhost:1522:xe

# ??? ???? ??? ??
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ?? CMD?? ??? BicLog ?? ?? ??
spring.datasource.username=biclog
spring.datasource.password=biclog123


# ==========================================================
# 2. SPRING DATA JPA SETTINGS (JPA / ?????? ??)
# ==========================================================
# ??? 12c ?? ??? ?? SQL ???(Dialect) ??
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# ???? SQL ???? ????? ???? ??? ??
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# DDL ?? ?? ??
# ('none'?? ?? ???? ??? ???? ??? ??, DBeaver?? ?? ??? ? ?? ?????.)
spring.jpa.hibernate.ddl-auto=none